[package]
name = "benchmarks"
version = "0.1.0"
edition = "2021"


[dependencies]
objectmap = { path = ".." }

[dev-dependencies]
criterion = { version = "0.5.1", features = ["html_reports"] }
rand = { version = "0.8" }
fnv = "1.0.7"

[[bench]]
name = "suite"
harness = false
