name: Audit

on: [push, pull_request]

jobs:
  audit:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - name: Install cargo-deny
        run: cargo -v install cargo-deny

      - name: Audit
        run: |
          cargo xtask audit
