name: Benchmarks

on: [push, pull_request]

jobs:
  benchmarks:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Rust
        uses: dtolnay/rust-toolchain@stable

      - name: Configure cache
        uses: Swatinem/rust-cache@v2

      - name: Run Benchmarks
        run: |
          cargo bench -p benchmarks

      - name: Deploy Reports
        if: github.ref == 'refs/heads/main'
        uses: JamesIves/github-pages-deploy-action@releases/v4
        with:
          branch: gh-pages
          folder: target/criterion/
          git-config-name: kl-botsu
          git-config-email: botsu@khonsulabs.com
          target-folder: /benchmarks/
          clean: true
